version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ./:/usr/src/app
      - "~/.composer.sh:/root/.composer.sh"
      - "~/.ssh:/root/.ssh-local:ro"
    networks:
      - compiler
    environment:
      - LOCAL_ENV=1
      - COMPOSER_ALLOW_SUPERUSER=1

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "11152:80"
    networks:
      - compiler
    depends_on:
      - php-fpm


networks:
  compiler:
      external: true